version: '3.8'

services:
  # 主域名应用容器 - 使用唯一名称
  colletools-app-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: colletools-app-prod-${DEPLOY_ID:-default}
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DOMAIN=${PRIMARY_DOMAIN}
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    networks:
      - colletools-prod-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 第二域名应用容器 - 使用唯一名称
  colletools-app-secondary-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: colletools-app-secondary-prod-${DEPLOY_ID:-default}
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DOMAIN=${SECONDARY_DOMAIN}
    volumes:
      - ./logs-secondary:/app/logs
    networks:
      - colletools-prod-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # nginx代理 - 使用项目特定名称
  colletools-nginx-prod:
    image: nginx:alpine
    container_name: colletools-nginx-prod-${DEPLOY_ID:-default}
    restart: unless-stopped
    ports:
      # 使用环境变量配置端口，默认使用非标准端口避免冲突
      - "${HTTP_PORT:-8080}:80"
      - "${HTTPS_PORT:-8443}:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./logs/nginx:/var/log/nginx
      - colletools-certbot-www:/var/www/certbot:ro
    environment:
      - PRIMARY_DOMAIN=${PRIMARY_DOMAIN}
      - SECONDARY_DOMAIN=${SECONDARY_DOMAIN}
    depends_on:
      - colletools-app-prod
      - colletools-app-secondary-prod
    networks:
      - colletools-prod-network
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 主域名 SSL 证书管理
  colletools-certbot-primary:
    image: certbot/certbot
    container_name: colletools-certbot-primary-${DEPLOY_ID:-default}
    volumes:
      - ./ssl:/etc/letsencrypt
      - colletools-certbot-www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email ${SSL_EMAIL} --agree-tos --no-eff-email -d ${PRIMARY_DOMAIN} -d www.${PRIMARY_DOMAIN}
    depends_on:
      - colletools-nginx-prod
    networks:
      - colletools-prod-network

  # 第二域名 SSL 证书管理
  colletools-certbot-secondary:
    image: certbot/certbot
    container_name: colletools-certbot-secondary-${DEPLOY_ID:-default}
    volumes:
      - ./ssl:/etc/letsencrypt
      - colletools-certbot-www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email ${SSL_EMAIL} --agree-tos --no-eff-email -d ${SECONDARY_DOMAIN} -d www.${SECONDARY_DOMAIN}
    depends_on:
      - colletools-nginx-prod
    networks:
      - colletools-prod-network

volumes:
  uploads:
    driver: local
  logs:
    driver: local
  ssl:
    driver: local
  colletools-certbot-www:
    driver: local

networks:
  colletools-prod-network:
    driver: bridge
    name: colletools-prod-network-${DEPLOY_ID:-default}