version: '3.8'

services:
  # Colletools 应用容器
  colletools-app:
    build:
      context: .
      dockerfile: Dockerfile.simple
    container_name: colletools-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DOMAIN=colletools.com
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    networks:
      - colletools-network
    ports:
      - "3000:3000"

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./logs/nginx:/var/log/nginx
    environment:
      - PRIMARY_DOMAIN=colletools.com
      - SECONDARY_DOMAIN=colletools.com
    depends_on:
      - colletools-app
    networks:
      - colletools-network

networks:
  colletools-network:
    driver: bridge
